import { IDictionary } from '../types';

export default {
    'Type something': 'Zacznij wpisywać',

    // About
    'Advanced': 'Zaawansowane',
    'About Jodit': 'O Jodit',
    'Jodit Editor': 'Edytor Jodit',
    'Free Non-commercial Version': 'Darmowa niekomercyjna wersja',
    'GNU General Public License, version 2 or later':
        'GNU General Public License, wersja 2 lub późniejsza',
    "Jodit User's Guide": 'Poradnik Jodit',
    'contains detailed help for using':
        'zawiera szczegółową pomoc',
    'For information about the license, please go to our website:':
        'Proszę odwiedzić naszą stronę internetową w celu zapoznania się z licencją',
    'Buy full version': 'Kup pełną wersję',
    'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
        'Copyright © XDSoft.net - Chupurnov Valeriy. Wszystkie prawa zastrzeżona.',

    // Toolbar
    'Anchor': 'Link',
    'Open in new tab': 'Otwórz w nowej karcie',
    'Open editor in fullsize': 'Otwórz edytor w pełnym rozmiarze',
    'Clear Formatting': 'Wyczyść formatowanie',
    'Fill color or set the text color': 'Zmień kolor wypełnienia lub tekstu',
    'Redo': 'Przywróć',
    'Undo': 'Cofnij,
    'Bold': 'Pogrubienie',
    'Italic': 'Kursywa',
    'Insert Unordered List': 'Lista nieuporządkowana',
    'Insert Ordered List': 'Lista uporządkowana',
    'Align Center': 'Wyśrodkuj',
    'Align Justify': 'Wyjustuj',
    'Align Left': 'Wyrównaj do lewej',
    'Align Right': 'Wyrównaj do prawej',
    'Insert Horizontal Line': 'Wstaw linię poziomą',
    'Insert Image': 'Wstaw obrazek',
    'Insert file': 'Wstaw plik',
    'Insert youtube/vimeo video': 'Wstaw wideo YouTube/Vimeo',
    'Insert link': 'Wstaw link',
    'Font size': 'Rozmiar czcionki',
    'Font family': 'Czcionka',

    'Insert format block': 'Wstaw format blokowy',
    'Normal': 'Normalny',
    'Heading 1': 'Nagłówek 1',
    'Heading 2': 'Nagłówek 2',
    'Heading 3': 'Nagłówek 3',
    'Heading 4': 'Nagłówek 4',
    'Quote': 'Cytat',
    'Code': 'Kod',

    'Insert': 'Wstaw',
    'Insert table': 'Wstaw tabelę',

    'Decrease Indent': 'Zmniejsz wcięcie',
    'Increase Indent': 'Zwiększ wcięcie',
    'Select Special Character': 'Zaznacz znak specjalny',
    'Insert Special Character': Wstaw znak specjalny',

    'Paint format': 'Kopiuj format',
    'Change mode': 'Zmień tryb',

    // plugin Image
    'Margins': 'Marginesy',
    'top': 'Góra',
    'right': 'Prawo',
    'bottom': 'Dół',
    'left': 'Lewo',
    'Styles': 'Styl CSS',
    'Classes': 'Klasa CSS',
    'Align': 'Wyrównanie',
    'Right': 'Prawo',
    'Center': 'Środek',
    'Left': 'Lewo',
    '--Not Set--': '--Nie ustawiono--',
    'Src': 'Źródło',
    'Title': 'Tytuł',
    'Alternative': 'Tekst zastępczy',
    'Link': 'Link',
    'Open link in new tab': 'Otwórz link w nowej karcie',
    'Image': 'Obrazek',
    'file': 'Plik',
    'Advansed': 'Zaawansowane',
    'Image properties': 'Ustawienia obrazka',
    'Cancel': 'Anuluj',
    'Ok': 'OK',

    // plugin paste
    'Your code is similar to HTML. Keep as HTML?':
        'Twój kod jest podobny do HMTLa. Pozostawić jako HTML?',
    'Paste as HTML': 'Wklej jako HTML',
    'Keep': 'Zachowaj oryginał',
    'Clean': 'Wyczyść',
    'Insert as Text': 'Wstaw jako tekst',
    'Word Paste Detected': 'Wykryto wklejenie z WORDa',

    'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
        'Wklejona treść pochodzi z documentu Microsoft Word/Excel. Chcesz zachować formatowanie czy chcesz je wyczyścić?',

    'Insert only Text': 'Wstaw tylko tekst',

    // File Browser module
    'File Browser': 'Przeglądarka plików',
    'Error on load list': 'Błąd przy wczytywaniu listy',
    'Error on load folders': 'Błąd przy wczytywaniu folderów',
    'Are you sure?': 'Jesteś pewien?',
    'Enter Directory name': 'Wpisz nazwę katalogu',
    'Create directory': 'Stwórz katalog',
    'type name': 'Wpisz nazwę',

    // Form module
    'Drop image': 'Wrzuć obrazek',
    'Drop file': 'Wrzuć plik',
    'or click': 'albo kliknij',
    'Alternative text': 'Tekst zastępczy',
    'Browse': 'Przeglądaj',
    'Upload': 'Wgraj',
    'Background': 'Tło',
    'Text': 'Tekst',

    // popap module
    'Top': 'Góra',
    'Middle': 'Środek',
    'Bottom': 'Dół',
    'Insert column before': 'Wstaw kolumnę przed',
    'Insert column after': 'Wstaw kolumnę po',
    'Insert row above': 'Wstaw wiersz powyżej',
    'Insert row below': 'Wstaw wiersz poniżej',
    'Delete table': 'Usuń tabelę',
    'Delete row': 'Usuń wiersz',
    'Delete column': 'Usuń kolumnę',
    'Empty cell': 'Wyczyść komórkę',

    'Delete': 'Usuń',
    'Strike through': 'Przekreślenie',
    'Underline': 'Podkreślenie',
    'Break': 'Podział',
    'Search for': 'Wyszukaj',
    'Replace with': 'Zastąp',
    'Replace': 'Zastąp',
    'Edit': 'Edytuj',
    'Vertical align': 'Orientacja pionowa',
    'Horizontal align': 'Orientacja pozioma',
    'Filter': 'Filtruj',
    'Sort by changed': 'Sortuj wg zmian',
    'Sort by name': 'Sortuj wg nazwy',
    'Sort by size': 'Sortuj wg rozmiaru',
    'Add folder': 'Dodaj folder',
    'Split vertical': 'Podziel pionowo',
    'Split horizontal': 'Podziel poziomo',
    'Merge': 'Połącz',
    'Add column': 'Dodaj kolumnę',
    'Add row': 'Dodaj wiersz',
    'Border': 'Obramowanie',
    'Embed code': 'Wstaw kod',
    'Update': 'Aktualizuj',
    'superscript': 'Indeks górny',
    'subscript': 'Indeks dolny',
    'Cut selection': 'Wytnij zaznaczenie',
    'Paste': 'Wklej',
    'Choose Content to Paste': 'Wybierz treść do wklejenia',

    // stat
    'Chars: %d': 'Znaki: %d',
    'Words: %d': 'Słowa: %d',

    'All': 'Wybierz wszystko',
    'Select %s': 'Zaznacz: %s',
    'Select all': 'Zaznacz wszystko',
    'source': 'Źródło',
    'bold': 'Pogrubienie',
    'italic': 'Kursywa',
    'brush': 'Pędzel',
    'link': 'Link',
    'undo': 'Cofnij',
    'redo': 'Przywróć',
    'table': 'Tabela',
    'image': 'Obrazek',
    'eraser': 'Gumka',
    'paragraph': 'Paragraf',
    'fontsize': 'Rozmiar czcionki',
    'video': 'Video',
    'font': 'Czcionka',
    'about': 'O',
    'print': 'Drukuj',
    'symbol': 'Symbol',
    'underline': 'Podkreślenie',
    'strikethrough': 'Przekreślenie',
    'indent': 'Wcięcie',
    'outdent': 'Zmniejsz wcięcie',
    'fullsize': 'Pełen rozmiar',
    'shrink': 'Zmniejsz',
    'copyformat': 'Skopiuj format',
    'hr': 'Linia',
    'ul': 'Lista wypunktowana',
    'ol': 'Lista numerowana',
    'cut': 'Wytnij',
    'selectall': 'Zaznacz wszystko',
    'Open link': 'Otwórz link',
    'Edit link': 'Edytuj link',
    'No follow': 'Atrybut No-follow',
    'Unlink': 'Usuń link',
    ' URL': 'URL',
    'Reset': 'Resetuj',
    'Save': 'Zapisz',
    'Save as ...': 'Zapisz jako',
    'Resize': 'Zmień rozmiar',
    'Crop': 'Przytnij',
    'Width': 'Szerokość',
    'Height': 'Wysokość',
    'Keep Aspect Ratio': 'Zachowaj proporcje',
    'Yes': 'Tak',
    'No': 'Nie',
    'Remove': 'Usuń',
    'Select': 'Zaznacz',
    'You can only edit your own images. Download this image on the host?': 'Możesz edytować tylko swoje obrazki. Pobrać?',
    'The image has been successfully uploaded to the host!': 'Obrazek został pomyślnie przesłany',
    'palette': 'Paleta',
} as IDictionary<string>;
